---
title: "analysis"
author: "Patrick"
date: "2023-10-12"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(RSocrata)
library(lubridate)
library(sf)
library(leaflet)
library(DBI)
library(RPostgreSQL)

options(scipen = 99)

knitr::opts_chunk$set(echo = TRUE)
```

```{r}
storefront_vacancies <- read.socrata("https://data.cityofnewyork.us/resource/92iy-9c3n.csv")

storefront_vacancies_clean <- storefront_vacancies %>% 
  separate(reporting_year, sep = " and ", into = c("year_12_31", "year_6_30")) %>% 
  mutate(date = as.Date(paste0(year_12_31, "-12-31")),
         year = year(date),
         cb = case_when(
           str_length(as.character(community_board))  < 3 & borough == "MANHATTAN" ~ paste0(1, str_pad(as.character(community_board), 2, "left", pad = "0")),
           str_length(as.character(community_board))  < 3 & borough == "BRONX" ~ paste0(2, str_pad(as.character(community_board), 2, "left", pad = "0")),
           str_length(as.character(community_board))  < 3 & borough == "BROOKLYN" ~ paste0(3, str_pad(as.character(community_board), 2, "left", pad = "0")),
           str_length(as.character(community_board))  < 3 & borough == "QUEENS" ~ paste0(4, str_pad(as.character(community_board), 2, "left", pad = "0")),
           str_length(as.character(community_board))  < 3 & borough == "STATEN ISLAND" ~ paste0(5, str_pad(as.character(community_board), 2, "left", pad = "0")),
           str_length(as.character(community_board)) == 3 ~ as.character(community_board)
         )
       )

```

Vacancies are down over time
```{r}
store_summary_time <- storefront_vacancies_clean %>% 
  group_by(year) %>% 
  summarize(total = n(),
            vacant = sum(vacant_on_12_31 == "YES"),
            not_vacant = sum(vacant_on_12_31 == "NO")) %>% 
  arrange(year) %>% 
  mutate(vacant_rate = vacant/(vacant+not_vacant),
         change_vacancies = vacant - lag(vacant),
         per_point_change_vacant = vacant_rate - lag(vacant_rate),
         per_change_vacant_rate = (vacant_rate/lag(vacant_rate))-1)

store_summary_time

ggplot(store_summary_time)+
  geom_line(mapping = aes(x = year, y = vacant_rate))
```


```{r}
cb_store_summary_time <- storefront_vacancies_clean %>% 
  group_by(year, cb) %>% 
  summarize(total = n(),
            vacant = sum(vacant_on_12_31 == "YES"),
            not_vacant = sum(vacant_on_12_31 == "NO")) %>% 
  arrange(cb, year) %>% 
  group_by(cb) %>% 
  mutate(vacant_rate = vacant/(vacant+not_vacant),
         change_vacancies = vacant - lag(vacant),
         per_point_change_vacant = vacant_rate - lag(vacant_rate),
         per_change_vacant_rate = (vacant_rate/lag(vacant_rate))-1)

cb_store_summary_time


cb_store_summary_time %>% filter(year == "2022-12-31") %>% 
  arrange(desc(per_change_vacant_rate))


```
shapify the cb data
```{r}

community_boards_sf <- read.socrata("https://data.cityofnewyork.us/resource/jp9i-3b7y.csv") %>% 
  st_as_sf(wkt = "the_geom") %>% 
  mutate(cb = as.character(boro_cd)) %>% 
  st_set_crs(2263)


cb_summary_sf <- community_boards_sf %>% 
  left_join(cb_store_summary_time, by = "cb")


```

map cb data
```{r}

pal <- colorNumeric(
  palette = c("#225E2B", "#ECECD5", "#BF1512"),
  domain = cb_summary_sf$vacant_rate)

pal_pp <- colorNumeric(
  palette = c("#225E2B", "#ECECD5", "#BF1512"),
  domain = cb_summary_sf$per_point_change_vacant)


map <- leaflet(filter(cb_summary_sf, year == "2022")) %>% 
  addProviderTiles(provider = "CartoDB.Positron") %>% 
  addPolygons(color = ~pal(vacant_rate),
              opacity = 0.9,
              weight = 0.5,
              group = "Vacancy Rate") %>% 
  addPolygons(color = ~pal_pp(per_point_change_vacant),
              opacity = 0.9,
              weight = 0.5,
              group = "Change in Vacancy Rate") %>% 
    addLayersControl(
      baseGroups = c("Vacancy Rate", "Change in Vacancy Rate"),
      #overlayGroups = c("Equity"),
      options = layersControlOptions(collapsed = F)
    )

map
```




```{r}

open_streets_locations <- read.socrata("https://data.cityofnewyork.us/resource/uiay-nctu.csv") %>% 
  st_as_sf(wkt = "the_geom") %>% 
  st_set_crs(st_crs(cb_summary_sf)) %>% 
  st_transform(st_crs(cb_summary_sf))

ggplot()+
  geom_sf(open_streets_locations, mapping = aes())

leaflet(open_streets_locations, options = leafletOptions(crs = leafletCRS(code = "EPSG:2263"))) %>% 
  addProviderTiles(provider = "CartoDB.Positron") %>% 
  addPolylines(color = "blue")

```




```{r}
connec <- dbConnect(dbDriver("PostgreSQL"), dbname = "nycdb", host = "nyc-db.cluster-custom-ckvyf7p6u5rl.us-east-1.rds.amazonaws.com", port = "5432", user = "anon", password = "tenantpower")

bbls_coords <- dbGetQuery(connec, "SELECT latitude, longitude, bbl FROM pluto_latest") %>% 
  rename(latitude_pluto = latitude,
        longitude_pluto = longitude
        )
```


```{r}
open_streets_locations_sf <- st_read("open_streets_reprojected.geojson") %>% 
  st_set_crs(st_crs(cb_summary_sf)) %>% 
  st_transform(st_crs(cb_summary_sf))

open_streets_buffer <- st_buffer(open_streets_locations_sf, dist = .0005)

storefront_vacancies_sf <- storefront_vacancies_clean %>% 
  mutate(bbl = as.character(bbl)) %>% 
  left_join(bbls_coords, by = "bbl")%>% 
  filter(!is.na(longitude_pluto)) %>% 
  st_as_sf(coords = c("longitude_pluto", "latitude_pluto")) %>%
  st_set_crs(st_crs(open_streets_locations)) %>% 
  st_transform(st_crs(open_streets_locations)) %>% 
  mutate(
        open_street = if_else(
                              lengths(st_intersects(.,open_streets_buffer))>0,
                              T,
                              F)
  )

ggplot()+
  geom_sf(open_streets_buffer, mapping = aes())+
  geom_sf(storefront_vacancies_sf, mapping = aes(color = open_street))


```

```{r}

open_street_summary <- as.data.frame(storefront_vacancies_sf) %>% 
  group_by(year, open_street) %>% 
  





```

